Import the physical code from capture to tikiClient
tiki/publish-client-ios pull request #59
Opened 2024-04-02 20:18 UTC by JesseMonteiro

close #58

2024-04-03 12:58 UTC, ricardobrg requested changes

2024-04-03 12:58 UTC, ricardobrg commented on Example/TikiClient/URLShemeExample.swift
fix filename `URLScheme...`

2024-04-03 12:58 UTC, ricardobrg commented on Physical/Camera.swift
The client lib should not have any UI. The UI should be in the Example app and it calls the function in the client lib that:
- check/ask the permission
- open the camera
- return the UIImage

2024-04-03 12:58 UTC, ricardobrg commented on TikiClient/Classes/Util/Coordinator.swift
This should be in the Example app. No UI in the client lib.

2024-04-03 20:11 UTC, JesseMonteiro commented
Issues solved

2024-04-04 11:28 UTC, ricardobrg requested changes

2024-04-04 11:28 UTC, ricardobrg commented on Physical/ImagePicker.swift
move this code to TikiClient/Classes/Capture

2024-04-04 11:28 UTC, ricardobrg commented on TikiClient/Classes/Capture/CaptureService.swift
create a CaptureScan class and move this code into it. With this, the CaptureService doesn't need to extend all these classas. The scan function call the CaptureScan class.

2024-04-04 11:28 UTC, ricardobrg commented on TikiClient/Classes/Capture/PublishingStatusEnum.swift
this file can be removed, we will not use it now

2024-04-04 14:07 UTC, JesseMonteiro commented on Physical/ImagePicker.swift
solve

2024-04-04 14:52 UTC, merged